#!/usr/bin/env node
/**
 * Looks up one Firebase user by email and prints SQL for app_users + user_role_mapping.
 *
 * Usage (from backend/, with backend/.env containing FIREBASE_SERVICE_ACCOUNT_JSON):
 *   node scripts/add_firebase_user_to_supabase_sql.js systemadmin@test.com sys_admin "System Admin"
 *
 * Role app_id must match roles.app_id: sys_admin, dept_head, supervisor, general
 *
 * Copy printed SQL into Supabase SQL Editor and run.
 */
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const admin = require('firebase-admin');

const json = process.env.FIREBASE_SERVICE_ACCOUNT_JSON || '';
if (!json) {
  console.error('Missing FIREBASE_SERVICE_ACCOUNT_JSON in backend/.env');
  process.exit(1);
}
admin.initializeApp({ credential: admin.credential.cert(JSON.parse(json)) });

function esc(s) {
  return String(s).replace(/'/g, "''");
}

async function main() {
  const email = (process.argv[2] || 'systemadmin@test.com').trim().toLowerCase();
  const role = (process.argv[3] || 'sys_admin').trim();
  const displayFallback = process.argv[4] || email.split('@')[0];

  let rec;
  try {
    rec = await admin.auth().getUserByEmail(email);
  } catch (e) {
    console.error('Firebase Auth: user not found:', email, e.message);
    process.exit(1);
  }

  const displayName = esc(rec.displayName || displayFallback);
  const uid = esc(rec.uid);
  const em = esc(email);

  console.error('OK', email, '->', rec.uid, 'role:', role);

  const sql = `-- Generated by: node scripts/add_firebase_user_to_supabase_sql.js
-- Run in Supabase SQL Editor
-- Optional: add a staff row first if you need staff_id linkage:
-- INSERT INTO staff (app_id, name, email) VALUES ('system_admin', 'System Admin', '${em}')
-- ON CONFLICT (app_id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email;

BEGIN;

INSERT INTO app_users (firebase_uid, email, display_name, staff_id)
VALUES (
  '${uid}',
  '${em}',
  '${displayName}',
  (SELECT id FROM staff WHERE lower(email) = lower('${em}') LIMIT 1)
)
ON CONFLICT (firebase_uid) DO UPDATE SET
  email = EXCLUDED.email,
  display_name = EXCLUDED.display_name,
  staff_id = EXCLUDED.staff_id,
  updated_at = now();

DELETE FROM user_role_mapping urm
USING app_users au
WHERE urm.app_user_id = au.id
  AND au.firebase_uid = '${uid}';

INSERT INTO user_role_mapping (app_user_id, role_id)
SELECT au.id, r.id
FROM app_users au
CROSS JOIN roles r
WHERE au.firebase_uid = '${uid}'
  AND r.app_id = '${esc(role)}'
ON CONFLICT (app_user_id, role_id) DO NOTHING;

COMMIT;
`;
  console.log(sql);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
