#!/usr/bin/env node
/**
 * Looks up Firebase Auth users by email and prints SQL to upsert app_users + user_role_mapping.
 *
 * Usage (from backend/):
 *   set FIREBASE_SERVICE_ACCOUNT_JSON=...   (or rely on ../.env via dotenv)
 *   node scripts/sync_app_users_from_firebase.js
 *
 * Copy the printed SQL into Supabase SQL Editor and run.
 */
require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const admin = require('firebase-admin');

const USERS = [
  { email: 'lunanchow@hku.hk', role: 'supervisor', displayName: 'Lunan CHOW' },
  { email: 'yang.wang@hku.hk', role: 'dept_head', displayName: 'Yang Wang' },
  { email: 'kenkylee@hku.hk', role: 'supervisor', displayName: 'Ken LEE' },
  { email: 'leec2@hku.hk', role: 'general', displayName: 'Calvin LEE' },
];

const json = process.env.FIREBASE_SERVICE_ACCOUNT_JSON || '';
if (!json) {
  console.error('Set FIREBASE_SERVICE_ACCOUNT_JSON (same as Railway backend).');
  process.exit(1);
}
admin.initializeApp({ credential: admin.credential.cert(JSON.parse(json)) });

function esc(s) {
  return String(s).replace(/'/g, "''");
}

async function main() {
  const rows = [];
  for (const u of USERS) {
    try {
      const rec = await admin.auth().getUserByEmail(u.email);
      rows.push({
        uid: rec.uid,
        email: u.email,
        role: u.role,
        displayName: rec.displayName || u.displayName,
      });
      console.error('OK', u.email, '->', rec.uid);
    } catch (e) {
      console.error('MISSING in Firebase Auth:', u.email, e.message);
    }
  }

  if (rows.length === 0) {
    console.error('No users found. Add the 4 accounts in Firebase Console first.');
    process.exit(1);
  }

  const values = rows
    .map(
      (r) =>
        `  ('${esc(r.uid)}', '${esc(r.email)}', '${esc(r.displayName)}', (SELECT id FROM staff WHERE lower(email) = lower('${esc(r.email)}') LIMIT 1))`,
    )
    .join(',\n');

  const unionParts = rows
    .map(
      (r) => `SELECT au.id, r.id
FROM app_users au
CROSS JOIN roles r
WHERE au.firebase_uid = '${esc(r.uid)}'
  AND r.app_id = '${esc(r.role)}'`,
    )
    .join('\nUNION ALL\n');

  const sql = `-- Generated by: node backend/scripts/sync_app_users_from_firebase.js
-- Run in Supabase SQL Editor

BEGIN;

INSERT INTO app_users (firebase_uid, email, display_name, staff_id)
VALUES
${values}
ON CONFLICT (firebase_uid) DO UPDATE SET
  email = EXCLUDED.email,
  display_name = EXCLUDED.display_name,
  staff_id = EXCLUDED.staff_id,
  updated_at = now();

DELETE FROM user_role_mapping urm
USING app_users au
WHERE urm.app_user_id = au.id
  AND au.firebase_uid IN (${rows.map((r) => `'${esc(r.uid)}'`).join(', ')});

INSERT INTO user_role_mapping (app_user_id, role_id)
${unionParts}
ON CONFLICT (app_user_id, role_id) DO NOTHING;

COMMIT;
`;
  console.log(sql);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
