-- =============================================================================
-- Import: user level tables v1.xlsx (staff, teams, roles reference, team_members,
--         subordinate_mapping, user_role_mapping where app_users exist)
-- Generated by: node scripts/generate_import_user_level_sql.js
-- Run in Supabase SQL Editor after backups. Review before executing.
-- =============================================================================

BEGIN;

-- 1) Roles (reference ids must match roles.app_id)
INSERT INTO roles (app_id, name) VALUES
  ('sys_admin', 'System Admin'),
  ('dept_head', 'Department Head'),
  ('supervisor', 'Supervisor'),
  ('general', 'General')
ON CONFLICT (app_id) DO NOTHING;

-- 2) Teams
INSERT INTO teams (name, app_id)
VALUES
  ('Fundraising Team', 'fundraising'),
  ('Alumni Affairs Team', 'alumni'),
  ('Advancement Intelligence Team', 'advancement_intel'),
  ('Admin Team', 'admin_team')
ON CONFLICT (app_id) DO UPDATE SET
  name = EXCLUDED.name;

-- 3) Staff
INSERT INTO staff (app_id, name, email)
VALUES
  ('yang_wang', 'Yang Wang', 'yang.wang@hku.hk'),
  ('jessicatai', 'Jessica Tai', 'jessicatai@hku.hk'),
  ('alanl', 'Alan LEUNG', 'alanl@hku.hk'),
  ('anthony_tai', 'Anthony TAI', 'anthony.tai@hku.hk'),
  ('auralu', 'Aura LU', 'auralu@hku.hk'),
  ('bhwl', 'Brenda LAU', 'bhwl@hku.hk'),
  ('leec2', 'Calvin LEE', 'leec2@hku.hk'),
  ('carolluk', 'Carol LUK', 'carolluk@hku.hk'),
  ('charlotte_siu', 'Charlotte SIU', 'charlotte.siu@hku.hk'),
  ('csmfung', 'Connie FUNG', 'csmfung@hku.hk'),
  ('lamyle', 'Elaine LAM', 'lamyle@hku.hk'),
  ('evatangc', 'Eva TANG', 'evatangc@hku.hk'),
  ('funali', 'Funa LI', 'funali@hku.hk'),
  ('hollyt', 'Holly TANG', 'hollyt@hku.hk'),
  ('ikichan', 'Iki CHAN', 'ikichan@hku.hk'),
  ('janellew', 'Janelle WONG', 'janellew@hku.hk'),
  ('janice_chan', 'Janice CHAN', 'janice.chan@hku.hk'),
  ('jodiehct', 'Jodie TSUI', 'jodiehct@hku.hk'),
  ('judityy', 'Judi TSANG', 'judityy@hku.hk'),
  ('karina_leung', 'Karina LEUNG', 'karina.leung@hku.hk'),
  ('katerina', 'Katerina AU', 'katerina@hku.hk'),
  ('kellylht', 'Kelly LEE', 'kellylht@hku.hk'),
  ('kenkylee', 'Ken LEE', 'kenkylee@hku.hk'),
  ('hkuken', 'Ken WONG', 'hkuken@hku.hk'),
  ('leodc', 'Leo CHAN', 'leodc@hku.hk'),
  ('lunanchow', 'Lunan CHOW', 'lunanchow@hku.hk'),
  ('melodytang', 'Melody TANG', 'melodytang@hku.hk'),
  ('mayw', 'May WONG', 'mayw@hku.hk'),
  ('monicaw', 'Monica WONG', 'monicaw@hku.hk'),
  ('olivew', 'Olive WONG', 'olivew@hku.hk'),
  ('pmkwan', 'Pauly WAN', 'pmkwan@hku.hk'),
  ('ronnielee', 'Ronnie LEE', 'ronnielee@hku.hk'),
  ('ruiwang', 'Rui WANG', 'ruiwang@hku.hk'),
  ('lscheng', 'Sally CHENG', 'lscheng@hku.hk'),
  ('ohyeawon', 'Sally OH', 'ohyeawon@hku.hk'),
  ('ssylo', 'Shirley LO', 'ssylo@hku.hk'),
  ('waikay_pang', 'Wai-kay PANG', 'waikay.pang@hku.hk'),
  ('winkyysw', 'Winky YEUNG', 'winkyysw@hku.hk'),
  ('emilygc', 'Cong GAO', 'emilygc@hku.hk')
ON CONFLICT (app_id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email;

-- 4) Subordinate mapping
-- Replace subordinate relationships from Excel (supervisor -> subordinate)
DELETE FROM subordinate_mapping;

INSERT INTO subordinate_mapping (supervisor_staff_id, subordinate_staff_id)
VALUES
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('funali@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('janice.chan@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('olivew@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ssylo@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('funali@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('janice.chan@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('olivew@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ssylo@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('bhwl@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('leec2@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('jodiehct@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('karina.leung@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('hkuken@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('leodc@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('waikay.pang@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('winkyysw@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('leec2@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('hkuken@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('waikay.pang@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('anthony.tai@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('carolluk@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('funali@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('hollyt@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ikichan@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('janellew@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ruiwang@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lscheng@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ohyeawon@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('auralu@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('charlotte.siu@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lamyle@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('evatangc@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('janice.chan@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('judityy@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('katerina@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('kellylht@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('melodytang@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('olivew@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('pmkwan@hku.hk') LIMIT 1)),
  ((SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('emilygc@hku.hk') LIMIT 1))
ON CONFLICT (supervisor_staff_id, subordinate_staff_id) DO NOTHING;

-- 5) Team members (derived)
-- Team membership derived from subordinate_mapping (Excel has no separate team_members sheet).
-- Directors: appear only as supervisor in that team; officers: appear only as subordinate; both -> director.
DELETE FROM team_members;

INSERT INTO team_members (team_id, staff_id, role)
VALUES
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('funali@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('janice.chan@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('yang.wang@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('kenkylee@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lunanchow@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('mayw@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('monicaw@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('olivew@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ssylo@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('jessicatai@hku.hk') LIMIT 1), 'director'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('bhwl@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('leec2@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('jodiehct@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('karina.leung@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('hkuken@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('leodc@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('waikay.pang@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'advancement_intel' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('winkyysw@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('anthony.tai@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('carolluk@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('hollyt@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ikichan@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('janellew@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ruiwang@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lscheng@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'alumni' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('ohyeawon@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('auralu@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('charlotte.siu@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('lamyle@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('evatangc@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('judityy@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('katerina@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('kellylht@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('melodytang@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('pmkwan@hku.hk') LIMIT 1), 'officer'),
  ((SELECT id FROM teams WHERE app_id = 'fundraising' LIMIT 1), (SELECT id FROM staff WHERE lower(email) = lower('emilygc@hku.hk') LIMIT 1), 'officer')
ON CONFLICT (team_id, staff_id) DO UPDATE SET
  role = EXCLUDED.role;

-- 6) User ↔ role (requires Firebase-linked app_users with same email)
-- Link app_users to roles (only rows where app_users already exists with matching email).
INSERT INTO user_role_mapping (app_user_id, role_id)
  -- userid 1 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('yang.wang@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 2 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('jessicatai@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 3 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('alanl@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 4 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('anthony.tai@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 5 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('auralu@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 6 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('bhwl@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 7 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('leec2@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 8 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('carolluk@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 9 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('charlotte.siu@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 10 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('csmfung@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 11 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('lamyle@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 12 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('evatangc@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 13 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('funali@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 14 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('hollyt@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 15 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ikichan@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 16 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('janellew@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 17 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('janice.chan@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 18 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('jodiehct@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 19 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('judityy@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 20 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('karina.leung@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 21 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('katerina@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 22 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('kellylht@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 23 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('kenkylee@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 24 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('hkuken@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 25 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('leodc@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 26 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('lunanchow@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 27 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('melodytang@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 28 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('mayw@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 29 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('monicaw@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 30 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('olivew@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 31 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('pmkwan@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 32 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ronnielee@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 33 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ruiwang@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 34 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('lscheng@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 35 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ohyeawon@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 36 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ssylo@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 37 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('waikay.pang@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 38 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('winkyysw@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 39 -> general
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('emilygc@hku.hk')
    AND r.app_id = 'general'
  UNION ALL
  -- userid 1 -> dept_head
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('yang.wang@hku.hk')
    AND r.app_id = 'dept_head'
  UNION ALL
  -- userid 2 -> dept_head
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('jessicatai@hku.hk')
    AND r.app_id = 'dept_head'
  UNION ALL
  -- userid 1 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('yang.wang@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 2 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('jessicatai@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 6 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('bhwl@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 9 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('charlotte.siu@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 13 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('funali@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 15 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ikichan@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 17 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('janice.chan@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 23 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('kenkylee@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 25 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('leodc@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 26 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('lunanchow@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 27 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('melodytang@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 28 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('mayw@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 29 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('monicaw@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 30 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('olivew@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 32 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ronnielee@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 36 -> supervisor
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('ssylo@hku.hk')
    AND r.app_id = 'supervisor'
  UNION ALL
  -- userid 7 -> sys_admin
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('leec2@hku.hk')
    AND r.app_id = 'sys_admin'
  UNION ALL
  -- userid 23 -> sys_admin
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('kenkylee@hku.hk')
    AND r.app_id = 'sys_admin'
  UNION ALL
  -- userid 24 -> sys_admin
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('hkuken@hku.hk')
    AND r.app_id = 'sys_admin'
  UNION ALL
  -- userid 26 -> sys_admin
  SELECT au.id, r.id
  FROM app_users au
  CROSS JOIN roles r
  WHERE lower(au.email) = lower('lunanchow@hku.hk')
    AND r.app_id = 'sys_admin'
ON CONFLICT (app_user_id, role_id) DO NOTHING;
COMMIT;

-- Verify
-- SELECT COUNT(*) FROM staff;
-- SELECT COUNT(*) FROM teams WHERE app_id IN ('fundraising','alumni','advancement_intel','admin_team');
-- SELECT COUNT(*) FROM subordinate_mapping;
-- SELECT COUNT(*) FROM team_members;
